#!/bin/sh

# exports
export EDITOR="nano"
export VISUAL="nano"
export BROWSER="thorium"

# Uncomment if using an Xorg window manager
#export QT_AUTO_SCREEN_SCALE_FACTOR=1
#export QT_ENABLE_HIGHDPI_SCALING=1
#export GDK_SCALE=2
#export GDK_DPI_SCALE=0.5
#export QT_QPA_PLATFORMTHEME="qt5ct"

# Uncomment if using a window manager
#export TERMINAL="kitty"
#export TERMINAL_PROG="kitty"
